### ISSUE TITLE
Dont work with grafana3 

### ISSUE THREAD

**Issue by jothoma1** [descrepes/grafana-telegraf-dashboard-generator#2]
Thanks for this great work, i'm trying to use it, but it doesnt work.
I m using latest version of grafana 3.0.0-beta7 and influxdb 0.12.2
My database is telegraf (i can make my own dahsboards, it works)

When i launch : 

```
grafana-telegraf-dashboard-generator-master]$ python generator.py --influxdb-user admin --influxdb-passwd XXX --databases 'telegraf' --hosts 127.0.0.1:8086 --dashboard-version 3 -v
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:requests.packages.urllib3.connectionpool:"GET /query?q=SHOW+DATABASES HTTP/1.1" 200 106
DEBUG:root:InfluxDB database telegraf :
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: 127.0.0.1
DEBUG:requests.packages.urllib3.connectionpool:"GET /query?q=SHOW+MEASUREMENTS&db=telegraf HTTP/1.1" 200 201
DEBUG:root: - Elasticsearch
```

It produced a "telegraf.json" file in the dashboards folder, but when i try to import it in grafana, nothing ? no error message but no dashboard as well
Any ideas ?

Thanks in advance!

**Comment by descrepes** [comment]
Hi,

It actually work on grafana beta6 and influxdb 0.11.

Is the telegraf.json generated a valid json file ?
Could you past it on a gist ?
I will try to import it.

Regards

**Comment by jothoma1** [comment]
Hi,
thanks for your help!
Here is the json generated: https://gist.github.com/jothoma1/b87cc230c1e0be084dd1684eccb2508c

Thanks in advance
Johan

**Comment by descrepes** [comment]
Hi,

Same as you, i can't import the dashboard manualy.
But the import using the API is working well.
You can import it using the following command:
`
curl "http://admin:admin@127.0.0.1:3001/api/dashboards/db" -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary @telegraf.json
`

I'm closing the issue cause it seems related to a grafana issue.

Please re-open it if it fail again when the 3.0 stable will be released.

Regards
